[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "race-cli"
version = "1.0.0"
description = "A powerful tool to measure executive efficiency!"
authors = [
    { name = "Ryan Tseng" }
]
requires-python = ">=3.10"
dependencies = [
    "click>=8.0"
]

[project.scripts]
race = "src.cli:main"

[tool.setuptools.packages.find]
where = ["."]
